name: Cryptic Device Microservice

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        cd app/
        pip install pipenv
        pipenv sync --dev
    - name: Test
      run: |
        cd app/
        pipenv run coverage
    - name: DEBUG
      run: |
        pwd
        ls -al
        cd app/
        pwd
        ls -al
    - name: SonarCloud scan
      if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action == 'opened')
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}